### ISSUE TITLE
Error in access data

### ISSUE THREAD

**Issue by MinLuke** [waldronlab/curatedMetagenomicDataAnalyses#47]
Hello to everyone,

I am currently trying to get access to the data contained at the curatedMetagenomicData repository but I get the following error message:

```
britol = BritoIL_2016.metaphlan_bugs_list.stool()
Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
```

How can me addressed this issue?
thank you a lot for you support

**Comment by schifferl** [comment]
You are using a very old version of our API - please refer to the documentation [here](https://waldronlab.io/curatedMetagenomicData/reference/curatedMetagenomicData.html).
